version: "3.7"
services:
   mongo:
    container_name: mongo-service
    image: mongo
    logging:
      driver: none
    expose:
      - 27017
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/data/db
   backend:
    container_name: back-end-express
    command: sh -c "npm run dev"
    restart: always 
    build: 
        context: .
        dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
   mongo_express:
    container_name: mongo_gui
    image: mongo-express
    logging:
      driver: none
    links:
      - mongo
    ports:
      - "8083:8081"
volumes:
  mongodb:
